export const reportings = [
  {
    SL: "1",
    Name: "Marble & Tile Traders’ Association of Siliguri Vs. C.T.O & Ors.",
    VST: "(2008)14 VST 455",
    Citation: "(2008) 51 STA 97",
    Court: "",
  },
  {
    SL: "2",
    Name: "Prashant Milan (P) Ltd. & Anr. Vs. CCT, West Bengal & Anr.",
    VST: "(2009) 1 CHN 265",
    Citation: "(2008) 52 STA 232 CAL (DB)",
    Court: "",
  },
  {
    SL: "3",
    Name: "Asit Baran Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 25 VST 124",
    Citation: "(2008) 52 STA 234",
    Court: "",
  },
  {
    SL: "4",
    Name: "Rotomac Electricals Pvt. Ltd. Vs. Addl.CCT, West Bengal & Ors.",
    VST: "(2009) 54 STA 342",
    Citation: "",
    Court: "",
  },
  {
    SL: "5",
    Name: "Asit Baran Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 25 VST 143",
    Citation: "(2009) 54 STA 256 CAL (DB)",
    Court: "",
  },
  {
    SL: "6",
    Name: "P.D. Prasad & Sons Pvt. Ltd Vs. ACCT & Ors.",
    VST: "(2009) 25 VST 335",
    Citation: "(2009) 54 STA 277 CAL (DB)",
    Court: "",
  },
  {
    SL: "7",
    Name: "Premier Diesel Pvt Ltd Vs. CCT, WB",
    VST: "(2009) 25 VST 195",
    Citation: "(2008) 52 STA 270",
    Court: "",
  },
  {
    SL: "8",
    Name: "JSK Marketing Private Limited Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 26 VST 272",
    Citation: "(2010) 55 STA 178 WBTT",
    Court: "",
  },
  {
    SL: "9",
    Name: "Pankaj Gupta Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 28 VST 57",
    Citation: "",
    Court: "",
  },
  {
    SL: "10",
    Name: "Sri Pradip Kumar Sanganeria Vs. CTO, Narendra Dutta Sarani Charge\n & Ors.",
    VST: "(2010) 55 STA 30 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "11",
    Name: "Nand Kishore Garg Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 30 VST 101 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "12",
    Name: "Howrah Tax Payers’ Association Vs. Government of West Bengal.",
    VST: "(2010) 31 VST 458",
    Citation: "(2009) 53 STA 276 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "13",
    Name: "ICICI Bank Ltd. Vs. JCST, Central Section & Ors.",
    VST: "(2010) 31 VST 178",
    Citation: "(2011) 59 STA 107 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "14",
    Name: "Indian Jute Mills’ Association Vs. DCST, CD & Ors.",
    VST: "(2010) 31 VST 108",
    Citation: "(2010) 55 STA 38 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "15",
    Name: "Gourangalal Chatterjee Vs. State of West Bengal",
    VST: "(2010) 32 VST 355 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "16",
    Name: "Bharti Airtel Ltd & Anr.Vs. ACST, Salt Lake Charge & Ors.",
    VST: "(2010) 34 VST 202",
    Citation: "(2010) 56 STA 184 WBTT",
    Court: "",
  },
  {
    SL: "17",
    Name: "BOC India Ltd. Vs. WBCTARB & Ors",
    VST: "(2010) 34 VST 448 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "18",
    Name: "Nursing Vanijya Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 34 VST 18 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "19",
    Name: "Calcutta Iron & Engineering Co. Pvt. Ltd Vs. ACCT, Corporate\n Division & Ors.",
    VST: "(2010) 55 STA 186 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "20",
    Name: "Sunita Lakhotia (Smt.) Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 34 VST 373",
    Citation: "(2010) 55 STA 234 WBTT",
    Court: "",
  },
  {
    SL: "21",
    Name: "Builders’ Association of India Vs. State of West Bengal",
    VST: "(2010) 35 VST 22",
    Citation: "(2010) 55 STA 224 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "22",
    Name: "Himanka Kumar Paul Vs. Additional CCT,West Bengal & Ors.",
    VST: "(2011) 38 VST 433 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "23",
    Name: "Ashok Kumar Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 41 VST 97 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "24",
    Name: "Epitome Petrochemicals Pvt. Ltd Vs. CCT West Bengal & Ors.",
    VST: "(2011) 41 VST 22",
    Citation: "(2011) 58 STA 95 WBTT",
    Court: "",
  },
  {
    SL: "25",
    Name: "JNRT Commercial (P) Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2011) 57 STA 237 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "26",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Deputy Commissioner of Sales Tax &\n Ors.",
    VST: "(2011) 42 VST 31 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "27",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Senior Joint Commissioner of\n Commercial Tax & Ors.",
    VST: "(2011) 42 VST 34 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "28",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Senior Joint Commissioner of\n Commercial Tax & Ors.",
    VST: "(2011) 42 VST 44 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "29",
    Name: "Maple Exports Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 42 VST 419 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "30",
    Name: "Super Spirit Warehouse Vs. State of West Bengal & Ors.",
    VST: "(2011) 57 STA 222 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "31",
    Name: "Maple Exports Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 42 VST 424 (2011) 58 STA 168 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "32",
    Name: "W.B. Foreign Liquor “off” and “on” Shop Owners’ Association &\n Another Vs. The Govt. of West Bengal & Ors.",
    VST: "(2011) 59 STA 27 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "33",
    Name: "Debabrata Roy Choudhury Vs. STO, Burdwan Charge & Anr.",
    VST: "(2012) 49 VST 231 STA 104",
    Citation: "",
    Court: "",
  },
  {
    SL: "34",
    Name: "Frostees Exports Pvt Ltd Vs. DCCT, Corporate Division & Ors.",
    VST: "(2012) 50 VST 392 (2011) 57 STA 36 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "35",
    Name: "Deb Scientific Vs. ACST, Central Section & Ors.",
    VST: "(2012) 52 VST 191 (2012) 60 STA 207 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "36",
    Name: "Hasmukh Parekh Vs. ASTO & Ors.",
    VST: "(2012) 52 VST 195 (2012) 60 STA 114 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "37",
    Name: "Angus Jute Works of the Angus Co. Ltd JCCT, Corporate Division &\n Ors",
    VST: "(2012) 53 VST 99 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "38",
    Name: "Angus Jute Works of the Angus Co. Ltd JCCT, Corporate Division &\n Ors",
    VST: "(2012) 53 VST 106 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "39",
    Name: "Auto Hitech (P) Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2010) 36 VST 198 (2012) 60 STA 17 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "40",
    Name: "Durgapada Sahoo Vs. State of West Bengal",
    VST: "2008 (2) CLJ (Cal) 80 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "41",
    Name: "ACCT, Corporate Division & Ors. Vs. Sambhu Prasad Agarwal",
    VST: "(2012) 60 STA 92 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "42",
    Name: "Epitome Petrochemicals Pvt. Ltd Vs. STO & Ors.",
    VST: "(2012) 54 VST 20 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "42A",
    Name: "Santosh Kumar Chowdhury Vs. Sr.JCCT Asansol Circle & Ors.",
    VST: "(2012) 55 VST 472 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "43",
    Name: "Sajan Kumar Bansal Vs. STO, Fairly Place Charge & Ors.",
    VST: "(2010) 2 CHN (Cal) 135 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "44",
    Name: "Gorachand Rakshit Vs. STO, Manohar Katra Charge & Ors.",
    VST: "(2010)1 CHN (Cal) 381 CAL",
    Citation: "",
    Court: "",
  },
  {
    SL: "45",
    Name: "New Ghosh Builders Vs. SrJCST, Durgapore Circle & Ors.",
    VST: "(2012) 56 VST 154 (2012) 60 STA 149 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "46",
    Name: "Trimurti Industries Ltd. Vs. STO, Siliguri Range & Ors.",
    VST: "(2012) 54 VST 405 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "47",
    Name: "Prabhash Chand Jain Vs. ACCT",
    VST: "(2012) 55 VST 306 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "48",
    Name: "Creative Polypack Ltd Vs. Addl. CCT & Ors",
    VST: "(2013) 61 STA 151 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "49",
    Name: "Delhi Assam Roadways Corporation Ltd. Vs. STO Siliguri Range &\n Ors.",
    VST: "(2013) 59 VST 433 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "50",
    Name: "Akshay Ispat & Ferro Alloys Pvt. Ltd. Vs. STO, Siliguri Range",
    VST: "(2013) 60 VST 274 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "51",
    Name: "Cipla Ltd. Vs. DCCT, Corporate Division & Ors.",
    VST: "(2013) 61 VST 445 (2013) 62 STA 194 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "52",
    Name: "Deepak Agarwal Vs. DCST, Manohardas Katra Charge & Ors.",
    VST: "(2013) 62 STA 7 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "53",
    Name: "PCM Tea Processing Pvt. Ltd. Vs. Assistant Commissioner Commercial\n Taxes & Ors.",
    VST: "(2013) 63 VST 288 (2014) 3 CHN (Cal) 258 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "54",
    Name: "PCM Tea Processing Pvt. Ltd. Vs. Assistant Commissioner Commercial\n Taxes & Ors.",
    VST: "(2013) 63 VST 293 (2013) 62 STA 29 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "55",
    Name: "ACST, Purulia Range Vs. Maa Chhinamastika Steel & Power Ltd.",
    VST: "(2013) 61 STA 264 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "56",
    Name: "Lalit Kumar Khaitan & Anr. Vs. JCCT, Barrackpore Range & Ors.",
    VST: "(2013) 61 STA 271 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "57",
    Name: "Gouranga Parbati Tea Co. Pvt. Ltd. Vs. A.I.T.O. Siliguri Charge &\n Ors",
    VST: "(2013) 62 STA 271 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "58",
    Name: "Kores (India) Ltd. & Anr. Vs. STO Duburdih Check Post & Ors.",
    VST: "(2013) 62 STA 180 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "59",
    Name: "Sri Jagannath Poddar Vs. STO & Ors.",
    VST: "(2014) 2 VST-OL 534 (2015) 65 STA 32 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "60",
    Name: "Braja Gopal Saha Vs. STO & Ors.",
    VST: "(2014) 2 VST-OL 649 (2014) 64 STA 255 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "61",
    Name: "Spasht Marketing Pvt. Ltd Vs. ASTO, Bureau of Investigation & Ors.",
    VST: "(2014) 71 VST 131 (2014) 64 STA 161 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "62",
    Name: "Buddhadeb Maity & Anr Vs. Sr.JCCT/ Medinipore Circle & Ors.",
    VST: "(2014) 63 STA 247 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "63",
    Name: "Rotomac Electrical Pvt. Ltd. Vs. Addl.CCT & Ors.",
    VST: "(2014) 63 STA 276 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "64",
    Name: "Sovan Das Vs. STO Behala Charge & Ors.",
    VST: "(2014) 71 VST 462 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "65",
    Name: "Kamala Board Box Pvt. Ltd. Vs. DCCT, 24 Pgs. Circle & Ors.",
    VST: "(2014) 64 STA 195 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "66",
    Name: "Kanknarrah Co. Ltd. v. Commercial Tax Officer",
    VST: "(2014) 3 VST-OL 540 (2014) 64 STA 281 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "67",
    Name: "Rina Dey v. Sales Tax Officer",
    VST: "(2014) 3 VST-OL 537 (2015) 65 STA 169 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "68",
    Name: "Deepak Agarwal Vs. DCST, Manohardas Katra Charge & Ors",
    VST: "(2014) 3 VST-OL 503 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "69",
    Name: "Himanka Kumar Paul Vs. Additional CCT,West Bengal & Ors.",
    VST: "(2014) 64 STA 288 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "70",
    Name: "Centex International Pvt. Ltd. Vs. STO & Ors.",
    VST: "(2014) 4 VST-OL 270 (2014) 64 STA 332 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "71",
    Name: "Suparna Ghosh Vs. ACST, Serampore Circle & Ors.",
    VST: "(2015) 3 VST-OL 525 (2015) 66 STA 91 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "72",
    Name: "Om Tubes Pvt. Ltd. Vs. ACST, Central Section & Ors.",
    VST: "(2015) 65 STA 53 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "73",
    Name: "Apsara Trade Centre Pvt. Ltd. Vs. ACST, Central Section & Ors.",
    VST: "(2015) 66 STA 119 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "74",
    Name: "Aloke Dutt Vs. STO, Siliguri Range & Ors.",
    VST: "(2015) 66 STA 178 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "75",
    Name: "Sant Lal Vs. JCCT, Howrah Division & Ors.",
    VST: "(2015) 67 STA 120 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "76",
    Name: "Usha Khaitan Vs. ACST, Kolkata North Commissionerate & Ors.",
    VST: "(2015) 68 STA 66 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "77",
    Name: "M/s Vikram Solar Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 68 STA 225 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "78",
    Name: "Isobar Developer & Marketing Pvt. Ltd. Vs. ACST, Central Section &\n Ors.",
    VST: "(2015) 69 STA 2 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "79",
    Name: "Sunil Kumar Sarda Vs. CST, West Bengal & Ors.",
    VST: "(2015) 69 STA 76 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "80",
    Name: "Ruchi Soya Industries Ltd. Vs. ACST, Kolkata Central\n Commissionerate & Ors.",
    VST: "(2015) 69 STA 138 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "81",
    Name: "M/s. N.R. Switch N Spares Ltd. Vs. ACCT, Kolkata Central\n Commissionerate & Ors.",
    VST: "(2015) 70 STA 123 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "82",
    Name: "Omprakash Agrawal Vs. STO & Ors.",
    VST: "(2015) 70 STA 194 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "83",
    Name: "Ratan Mal Lahoti Vs. STO & Ors.",
    VST: "(2015) 71 STA 83 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "84",
    Name: "Rahul Kumar Kedia Vs. DCCT, 24 Pgs. Circle & Ors.",
    VST: "(2015) 71 STA 191 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "85",
    Name: "Sweta Vincom Pvt. Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 72 STA 20 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "86",
    Name: "Deshabandhu Warehousing Pvt. Ltd. Vs. ACCT, Corporate Division &\n Ors.",
    VST: "(2015) 72 STA 105 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "87",
    Name: "N. Bose & Associates Pvt. Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 72 STA 168 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "88",
    Name: "Ashok Kumar Bhuwalka Vs. ACCT, Kolkata North Commissionerate &\n Ors.",
    VST: "(2015) 73 STA 105 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "89",
    Name: "ACCT, Corporate Division & Ors. Vs. M/s. Encon Equipment Ltd.",
    VST: "(2015) 73 STA 209 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "90",
    Name: "BHagirathi Enterprises Pvt. Ltd. Vs. ACCT, Corporate Division &\n Ors.",
    VST: "(2015) 74 STA 89 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "91",
    Name: "Ramesh Kumar Agarwal Vs. DCCT, 24 Pgs. Circle & Ors.",
    VST: "(2015) 74 STA 204 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "92",
    Name: "M/s. Saurav Petrochem (P) Ltd. Vs. ACCT, Kolkata South\n Commissionerate & Ors.",
    VST: "(2015) 74 STA 312 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "93",
    Name: "Eveready Industries India Ltd. Vs. ACCT, Kolkata South\n Commissionerate & Ors.",
    VST: "(2015) 74 STA 397 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "94",
    Name: "Virat Credit & Holdings Pvt. Ltd. Vs. ACCT, Corporate Division &\n Ors.",
    VST: "(2015) 75 STA 123 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "95",
    Name: "BLB Ltd. Vs. ACCT, Kolkata South Commissionerate & Ors.",
    VST: "(2015) 75 STA 240 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "96",
    Name: "Leena Power Tech Engineers Pvt. Ltd. Vs. ACST, Central Section &\n Ors.",
    VST: "(2015) 76 STA 127 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "97",
    Name: "Sri Subrata Basu & Ors. Vs. DCCT, 24 Pgs. Circle & Ors.",
    VST: "(2015) 76 STA 241 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "98",
    Name: "Ratnabali Investments Pvt. Ltd. Vs. ACCT, Kolkata South\n Commissionerate & Ors.",
    VST: "(2015) 76 STA 337 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "99",
    Name: "Ratnabali Investments Pvt. Ltd. Vs. ACCT, Kolkata South\n Commissionerate & Ors.",
    VST: "(2015) 77 STA 37 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "100",
    Name: "M/s. Hariyana Timber Trading Co. (P) Ltd. Vs. ACST, Central\n Section & Ors.",
    VST: "(2015) 77 STA 195 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "101",
    Name: "M/s. Hariyana Timber Trading Co. (P) Ltd. Vs. ACST, Central\n Section & Ors.",
    VST: "(2015) 77 STA 293 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "102",
    Name: "M/s. Hariyana Timber Trading Co. (P) Ltd. Vs. ACST, Central\n Section & Ors.",
    VST: "(2015) 78 STA 34 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "103",
    Name: "Kaustuv Ghosh Vs. ACST, Central Section & Ors.",
    VST: "(2015) 78 STA 136 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "104",
    Name: "Industrial Components Vs. STO & Ors.",
    VST: "(2015) 78 STA 213 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "105",
    Name: "Karnani Industrial Services Pvt. Ltd. Vs. ACCT, Corporate Division\n & Ors.",
    VST: "(2015) 78 STA 320 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "106",
    Name: "Karnani Properties Pvt. Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 79 STA 84 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "107",
    Name: "ACCT, Corporate Division & Ors. Vs. Shyam Sel & Power Ltd.",
    VST: "(2015) 79 STA 207 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "108",
    Name: "M/s. D.P. Sales Vs. ACST, Central Section & Ors.",
    VST: "(2015) 79 STA 305 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "109",
    Name: "Kamala Board Box Pvt. Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 79 STA 398 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "110",
    Name: "Superlink Commercial Pvt. Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2015) 80 STA 77 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "111",
    Name: "Prakash Poddar Vs. STO & Ors.",
    VST: "(2015) 80 STA 155 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "112",
    Name: "ACCT, Corporate Division & Ors. Vs. Vikas Kumar Jain",
    VST: "(2015) 80 STA 244 WBTT",
    Citation: "",
    Court: "WBTT",
  },
];
